export const CHANGE_RANDOM_LOCATION_HARE = "CHANGE_RANDOM_LOCATION_HARE";
export const HUNTER_CREATE = "HUNTER_CREATE";
export const HUNTER_DELETE = "DELETE";
export const SET__HARE_LOCATION = "SET__HARE_LOCATION";